name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        ports: ['5432:5432']
        env:
          database: myapp_test
          username: myapp
          password: password
          
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
      - name: Install gems
        run: |
          bundle install --jobs 4 --retry 3
      - name: Setup database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/myapp_test"
          RAILS_ENV: test
          DISABLE_SPRING: 1
        run: bundle exec rails db:prepare
      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/myapp_test"
          RAILS_ENV: test
          DISABLE_SPRING: 1
        run: bundle exec rails test
